version: '3'
services:
  web:
    build: ./backend
    container_name: web
    ports:
      - "5000:${PORT:-5000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5000}
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    restart: always
    depends_on:
      - web